### ISSUE TITLE
Not working as network printer

### ISSUE THREAD

**Issue by Justify87** [clawsoftware/clawPDF#14]
Print job and ini file are placed in claw-spooler folder of printserver but not placed in target folder as pdf. Nothing in the log file when printed from client with network printer.

is there a setting I can adjust to make it work? Seems like some kind of permission thing. But I am not allowed to configure clawmon.

**Comment by Kiuman** [comment]
Have the same issue. This is a key feature for me and I guess for many since there's no other open source solution that achieves this.

**Comment by victorromeo** [comment]
Having the same issue.  May we please get advice on the underlying cause of this and the path to achieve a workaround?

I had concerns that the print jobs were being initialised as the logged in user, on the current machine only, due to registry.  The CurrentUser settings are only accessible when the installing user is the one who performs the print task.

I believe it appropriate to move these to HKLM instead, so that the print spool can access the print when printing occurs from another user

**Comment by clawsoftware** [comment]
The functionality was implemented in version 0.9.0.

https://github.com/clawsoftware/clawPDF/wiki/Install-as-Network-Printer
