### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by poison64** [clawsoftware/clawPDF#26]
Is there a build instruction available somewhere?

When I tried to build (after extracting clawmon/x86 and clawmon/x64 from msi) i'm getting missing files from clawPDF_setup

![image](https://user-images.githubusercontent.com/32999079/81061706-1d5c7c00-8ed5-11ea-9d1b-0fb02aef3f2e.png)

And when I try to change configuration to "Any CPU" i'm getting missing openssl file:

![image](https://user-images.githubusercontent.com/32999079/81061759-3402d300-8ed5-11ea-94ef-ae0171fb69f1.png)

An instruction covering build from start to finish would be nice...

**Comment by twooclock** [comment]
See other issues and you'll be able to build. Yes it would be nice if maintainer @clawsoftware would add build procedure to readme and fix some criticall issues like for example #23 and #25.

**Comment by poison64** [comment]
I don't know if that's true, because none of these issues mention my problem with openssl header file...

**Comment by twooclock** [comment]
What I did was download [clawmon](https://github.com/clawsoftware/clawmon) and extract openssl files from there. Hope it helps.

**Comment by AloisH** [comment]
# clawPDF // How to compile

Using Microsoft visual studio 2019

# How to fix .dll missing

error MSB3030: Could not copy the file "clawPDF\clawPDF\clawmon\x86\SCPDFPRN.ppd" because it was not found.

Download and Install https://github.com/clawsoftware/clawPDF/releases/download/0.8.4/clawPDF_0.8.4_setup.msi
Then copy folder C:\Program Files (x86)\clawpdf\clawmon to your project inside clawPDF\clawPDF

You should now be able to compile

# How to compile the msi setup

ERROR: Unable to find source file for file 'license.rtf', located in '[TARGETDIR]', the file may be absent or locked.

- Go to build -> configuration manager
- Change clawPDF platform to Any CPU
- Change SetupHelper to Any CPU
- Change every project to Release instead of Debug
- Go to build -> build
- Replace ClawPDF/\_Build/clawmon by the one located in ClawPDF\ClawPDF\clawmon

You should now be able to compile the setup

**Comment by stargazerbooks** [comment]
Odd . . . when I follow the steps above it builds fine in VS2019. However I get no output when I print.

Installation form the source MSI prints fine:
https://github.com/clawsoftware/clawPDF/releases/download/0.8.4/clawPDF_0.8.4_setup.msi

But when I build the repo, it acts like it wants to print, asks for a file location, and then NO OUTPUT.

I'll need a working copy before I can test my changes. Any thoughts?  Does the .NET framework need to be the exact version, or can it be later?

**Comment by clawsoftware** [comment]
Since version 0.8.7 the code can be compiled without manual steps.
